In [25]:
import urllib
import os
import zipfile
import pandas as pd
import tensorflow as tf
import numpy as np

In [4]:
def download_and_extract_data():
    url = 'https://raw.githubusercontent.com/dicodingacademy/dicoding_dataset/main/household_power.zip'
    urllib.request.urlretrieve(url, 'household_power.zip')
    with zipfile.ZipFile('household_power.zip', 'r') as zip_ref:
        zip_ref.extractall()

def normalize_series(data, min, max):
    data = data - min
    data = data / max
    return data

def windowed_dataset(series, batch_size, n_past=24, n_future=24, shift=1):
    # YOUR CODE HERE
    dataset = tf.data.Dataset.from_tensor_slices(series)
    dataset = dataset.window(n_past + n_future, shift=shift, drop_remainder=True)
    dataset = dataset.flat_map(lambda window: window.batch(n_past + n_future))
    dataset = dataset.map(lambda window: (window[:n_past], window[n_future:, :1]))
    dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size).prefetch(1)
    return dataset

In [5]:
download_and_extract_data()
# Reads the dataset from the csv.
df = pd.read_csv('household_power_consumption.csv', sep=',',
                infer_datetime_format=True, index_col='datetime', header=0)
df

C:\Users\ideap\AppData\Local\Temp\ipykernel_13736\2888218216.py:3: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df = pd.read_csv('household_power_consumption.csv', sep=',',

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
datetime,,,,,,,
2006-12-16 17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
2006-12-16 17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2006-12-16 17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
2006-12-16 17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
2006-12-16 17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0
...,...,...,...,...,...,...,...
2007-02-14 17:19:00,0.636,0.140,241.16,2.6,0.0,0.0,0.0
2007-02-14 17:20:00,0.552,0.000,240.46,2.2,0.0,0.0,0.0
2007-02-14 17:21:00,0.538,0.000,239.74,2.2,0.0,0.0,0.0
2007-02-14 17:22:00,0.524,0.000,241.08,2.2,0.0,0.0,0.0
2007-02-14 17:23:00,0.544,0.000,241.62,2.2,0.0,1.0,0.0

In [18]:
new_df = df.iloc[0:24]
new_df

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
datetime,,,,,,,
2006-12-16 17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
2006-12-16 17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2006-12-16 17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
2006-12-16 17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
2006-12-16 17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0
2006-12-16 17:29:00,3.520,0.522,235.02,15.0,0.0,2.0,17.0
2006-12-16 17:30:00,3.702,0.520,235.09,15.8,0.0,1.0,17.0
2006-12-16 17:31:00,3.700,0.520,235.22,15.8,0.0,1.0,17.0
2006-12-16 17:32:00,3.668,0.510,233.99,15.8,0.0,1.0,17.0
2006-12-16 17:33:00,3.662,0.510,233.86,15.8,0.0,2.0,16.0
2006-12-16 17:34:00,4.448,0.498,232.86,19.6,0.0,1.0,17.0
2006-12-16 17:35:00,5.412,0.470,232.78,23.2,0.0,1.0,17.0
2006-12-16 17:36:00,5.224,0.478,232.99,22.4,0.0,1.0,16.0
2006-12-16 17:37:00,5.268,0.398,232.91,22.6,0.0,2.0,17.0
2006-12-16 17:38:00,4.054,0.422,235.24,17.6,0.0,1.0,17.0
2006-12-16 17:39:00,3.384,0.282,237.14,14.2,0.0,0.0,17.0
2006-12-16 17:40:00,3.270,0.152,236.73,13.8,0.0,0.0,17.0
2006-12-16 17:41:00,3.430,0.156,237.06,14.4,0.0,0.0,17.0
2006-12-16 17:42:00,3.266,0.000,237.13,13.8,0.0,0.0,18.0
2006-12-16 17:43:00,3.728,0.000,235.84,16.4,0.0,0.0,17.0
2006-12-16 17:44:00,5.894,0.000,232.69,25.4,0.0,0.0,16.0
2006-12-16 17:45:00,7.706,0.000,230.98,33.2,0.0,0.0,17.0
2006-12-16 17:46:00,7.026,0.000,232.21,30.6,0.0,0.0,16.0
2006-12-16 17:47:00,5.174,0.000,234.19,22.0,0.0,0.0,17.0

In [20]:
new_data = new_df.values
new_data = normalize_series(new_data, new_data.min(axis=0), new_data.max(axis=0))

C:\Users\ideap\AppData\Local\Temp\ipykernel_13736\756891246.py:9: RuntimeWarning: invalid value encountered in divide
  data = data / max

In [21]:
new_data

array([[1.23280561e-01, 7.91666667e-01, 1.62773045e-02, 1.38554217e-01,
                   nan, 5.00000000e-01, 5.55555556e-02],
       [2.71736309e-01, 8.25757576e-01, 1.11748334e-02, 2.77108434e-01,
                   nan, 5.00000000e-01, 0.00000000e+00],
       [2.73553076e-01, 9.43181818e-01, 9.74108122e-03, 2.77108434e-01,
                   nan, 1.00000000e+00, 5.55555556e-02],
       [2.75369842e-01, 9.50757576e-01, 1.16386944e-02, 2.77108434e-01,
                   nan, 5.00000000e-01, 5.55555556e-02],
       [5.19076045e-02, 1.00000000e+00, 1.98195159e-02, 6.02409639e-02,
                   nan, 5.00000000e-01, 5.55555556e-02],
       [3.29613288e-02, 9.88636364e-01, 1.70363498e-02, 3.61445783e-02,
                   nan, 1.00000000e+00, 5.55555556e-02],
       [5.65792889e-02, 9.84848485e-01, 1.73315341e-02, 6.02409639e-02,
                   nan, 5.00000000e-01, 5.55555556e-02],
       [5.63197508e-02, 9.84848485e-01, 1.78797335e-02, 6.02409639e-02,
                   nan, 5.00000000e-01, 5.55555556e-02],
       [5.21671425e-02, 9.65909091e-01, 1.26929240e-02, 6.02409639e-02,
                   nan, 5.00000000e-01, 5.55555556e-02],
       [5.13885284e-02, 9.65909091e-01, 1.21447246e-02, 6.02409639e-02,
                   nan, 1.00000000e+00, 0.00000000e+00],
       [1.53386971e-01, 9.43181818e-01, 7.92780636e-03, 1.74698795e-01,
                   nan, 5.00000000e-01, 5.55555556e-02],
       [2.78484298e-01, 8.90151515e-01, 7.59045290e-03, 2.83132530e-01,
                   nan, 5.00000000e-01, 5.55555556e-02],
       [2.54087724e-01, 9.05303030e-01, 8.47600574e-03, 2.59036145e-01,
                   nan, 5.00000000e-01, 0.00000000e+00],
       [2.59797560e-01, 7.53787879e-01, 8.13865227e-03, 2.65060241e-01,
                   nan, 1.00000000e+00, 5.55555556e-02],
       [1.02257981e-01, 7.99242424e-01, 1.79640719e-02, 1.14457831e-01,
                   nan, 5.00000000e-01, 5.55555556e-02],
       [1.53127433e-02, 5.34090909e-01, 2.59762166e-02, 1.20481928e-02,
                   nan, 0.00000000e+00, 5.55555556e-02],
       [5.19076045e-04, 2.87878788e-01, 2.42472801e-02, 0.00000000e+00,
                   nan, 0.00000000e+00, 5.55555556e-02],
       [2.12821178e-02, 2.95454545e-01, 2.56388631e-02, 1.80722892e-02,
                   nan, 0.00000000e+00, 5.55555556e-02],
       [0.00000000e+00, 0.00000000e+00, 2.59340474e-02, 0.00000000e+00,
                   nan, 0.00000000e+00, 1.11111111e-01],
       [5.99532832e-02, 0.00000000e+00, 2.04942228e-02, 7.83132530e-02,
                   nan, 0.00000000e+00, 5.55555556e-02],
       [3.41032961e-01, 0.00000000e+00, 7.21093025e-03, 3.49397590e-01,
                   nan, 0.00000000e+00, 0.00000000e+00],
       [5.76174410e-01, 0.00000000e+00, 0.00000000e+00, 5.84337349e-01,
                   nan, 0.00000000e+00, 5.55555556e-02],
       [4.87931482e-01, 0.00000000e+00, 5.18680948e-03, 5.06024096e-01,
                   nan, 0.00000000e+00, 0.00000000e+00],
       [2.47599273e-01, 0.00000000e+00, 1.35363077e-02, 2.46987952e-01,
                   nan, 0.00000000e+00, 5.55555556e-02]])

In [6]:
N_FEATURES = 7
BATCH_SIZE = 32  
N_PAST = 24 # Number of past time steps based on which future observations should be predicted
N_FUTURE = 24  # Number of future time steps which are to be predicted.
SHIFT = 1  # By how many positions the window slides to create a new window of observations.

In [22]:
# Normalizes the data
# DO NOT CHANGE THIS
data = df.values
split_time = int(len(data) * 0.5)
data = normalize_series(data, data.min(axis=0), data.max(axis=0))

# Splits the data into training and validation sets.
x_train = data[:split_time]
x_valid = data[split_time:]

In [23]:
new_data = data[0:24]
new_data

array([[0.43377912, 0.47826087, 0.04036551, 0.43564356, 0.        ,
        0.01282051, 0.85      ],
       [0.55716135, 0.49885584, 0.0355582 , 0.54950495, 0.        ,
        0.01282051, 0.8       ],
       [0.55867127, 0.56979405, 0.03420739, 0.54950495, 0.        ,
        0.02564103, 0.85      ],
       [0.56018119, 0.57437071, 0.03599523, 0.54950495, 0.        ,
        0.01282051, 0.85      ],
       [0.37446074, 0.60411899, 0.04370282, 0.37128713, 0.        ,
        0.01282051, 0.85      ],
       [0.35871441, 0.597254  , 0.04108065, 0.35148515, 0.        ,
        0.02564103, 0.85      ],
       [0.3783434 , 0.59496568, 0.04135876, 0.37128713, 0.        ,
        0.01282051, 0.85      ],
       [0.3781277 , 0.59496568, 0.04187525, 0.37128713, 0.        ,
        0.01282051, 0.85      ],
       [0.37467645, 0.58352403, 0.03698848, 0.37128713, 0.        ,
        0.01282051, 0.85      ],
       [0.37402934, 0.58352403, 0.03647199, 0.37128713, 0.        ,
        0.02564103, 0.8       ],
       [0.45880069, 0.56979405, 0.03249901, 0.46534653, 0.        ,
        0.01282051, 0.85      ],
       [0.56276963, 0.53775744, 0.03218117, 0.55445545, 0.        ,
        0.01282051, 0.85      ],
       [0.54249353, 0.54691076, 0.03301549, 0.53465347, 0.        ,
        0.01282051, 0.8       ],
       [0.547239  , 0.45537757, 0.03269766, 0.53960396, 0.        ,
        0.02564103, 0.85      ],
       [0.41630716, 0.48283753, 0.04195471, 0.41584158, 0.        ,
        0.01282051, 0.85      ],
       [0.34404659, 0.32265446, 0.04950338, 0.33168317, 0.        ,
        0.        , 0.85      ],
       [0.33175151, 0.17391304, 0.04787445, 0.32178218, 0.        ,
        0.        , 0.85      ],
       [0.34900777, 0.1784897 , 0.04918554, 0.33663366, 0.        ,
        0.        , 0.85      ],
       [0.3313201 , 0.        , 0.04946365, 0.32178218, 0.        ,
        0.        , 0.9       ],
       [0.38114754, 0.        , 0.0443385 , 0.38613861, 0.        ,
        0.        , 0.85      ],
       [0.6147541 , 0.        , 0.0318236 , 0.60891089, 0.        ,
        0.        , 0.8       ],
       [0.81018119, 0.        , 0.0250298 , 0.8019802 , 0.        ,
        0.        , 0.85      ],
       [0.73684211, 0.        , 0.02991657, 0.73762376, 0.        ,
        0.        , 0.8       ],
       [0.53710095, 0.        , 0.03778308, 0.52475248, 0.        ,
        0.        , 0.85      ]])

In [24]:
new_data.shape

(24, 7)

In [28]:
new_data = np.array(new_data)
test = new_data.reshape(1, 24, 7)
test.shape

(1, 24, 7)

In [8]:
train_set = windowed_dataset(x_train, BATCH_SIZE, N_PAST, N_FUTURE, SHIFT)
valid_set = windowed_dataset(x_valid, BATCH_SIZE, N_PAST, N_FUTURE, SHIFT)

In [9]:
for X_batch, y_batch in train_set.take(1):
    print(f"Input batch shape (X): {X_batch.shape}")
    print(f"Target batch shape (y): {y_batch.shape}")

Input batch shape (X): (32, 24, 7)
Target batch shape (y): (32, 24, 1)

In [10]:
# Code to define your model.
model = tf.keras.models.Sequential([
    # Whatever your first layer is, the input shape will be (N_PAST = 24, N_FEATURES = 7)
    tf.keras.layers.Dense(150, input_shape=(N_PAST, N_FEATURES), activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(N_FUTURE),
])

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 24, 150)           1200

 dense_1 (Dense)             (None, 24, 100)           15100

 dense_2 (Dense)             (None, 24, 24)            2424

=================================================================
Total params: 18,724
Trainable params: 18,724
Non-trainable params: 0
_________________________________________________________________

In [14]:
class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if (logs.get('mae') < 0.98):
            print("\nMAE < 0.098, stop training.")
            self.model.stop_training = True

In [16]:
custom_callback = myCallback()

optimizer = tf.keras.optimizers.SGD(learning_rate=0.001)

model.compile(loss=tf.keras.losses.Huber(), optimizer=optimizer, metrics=['mae'])

model.fit(train_set, epochs=100, validation_data=valid_set, callbacks=custom_callback)

Epoch 1/100

   1343/Unknown - 4s 3ms/step - loss: 0.0226 - mae: 0.1528
MAE < 0.098, stop training.
1349/1349 [==============================] - 7s 5ms/step - loss: 0.0226 - mae: 0.1527 - val_loss: 0.0183 - val_mae: 0.1331

In [29]:
predictions = model.predict(test)

1/1 [==============================] - 0s 91ms/step

In [30]:
print(predictions)

[[[ 4.07253653e-02  3.70558351e-02  4.22619656e-02  9.11220461e-02
    1.50761619e-01 -1.15869008e-01 -3.33699286e-02  6.35680184e-02
    7.08220378e-02 -1.16165608e-01 -2.36761943e-03  6.49421848e-03
    1.57196671e-02  1.15435570e-03  3.02761644e-02  4.99654338e-02
   -1.54396087e-01  1.77771021e-02  1.33567303e-03 -1.32038798e-02
    1.03247918e-01  5.70562147e-02  2.42415205e-01  6.18719235e-02]
  [ 5.84824681e-02  3.73493470e-02  5.50680980e-02  9.60335135e-02
    1.29508629e-01 -1.12749137e-01 -3.58284488e-02  6.36471361e-02
    5.72183430e-02 -1.33266285e-01 -2.46947184e-02  4.63211164e-03
    3.16593200e-02  2.71360353e-02  1.24320509e-02  6.60662726e-02
   -1.68408558e-01  5.60692325e-03 -4.76073846e-03 -1.92708056e-02
    9.34707224e-02  6.56936765e-02  2.46900290e-01  5.44941500e-02]
  [ 5.54883108e-02  4.05752026e-02  4.95963208e-02  1.01500213e-01
    1.36752814e-01 -1.29352719e-01 -3.85029539e-02  6.74869791e-02
    6.67477399e-02 -1.38079450e-01 -2.54615173e-02 -5.66219352e-03
    2.81510651e-02  2.56770365e-02  1.09835742e-02  6.86837584e-02
   -1.83984384e-01  4.82686609e-03 -1.92688592e-03 -2.59354878e-02
    1.01178549e-01  6.74441904e-02  2.70543993e-01  5.64008132e-02]
  [ 5.26156798e-02  4.11515795e-02  4.79766838e-02  1.01228252e-01
    1.39272779e-01 -1.30831793e-01 -3.90920863e-02  6.79583848e-02
    6.82063624e-02 -1.40628979e-01 -2.33960226e-02 -6.00100122e-03
    2.74061766e-02  2.68209353e-02  1.01058288e-02  6.89378679e-02
   -1.83888897e-01  2.64725834e-03 -7.61058182e-04 -2.50776540e-02
    1.00627534e-01  6.50055930e-02  2.72909880e-01  5.76093793e-02]
  [ 2.33674571e-02  4.69796881e-02  2.80314274e-02  7.88870305e-02
    1.51342914e-01 -1.36215761e-01 -3.95514816e-02  7.10139945e-02
    8.54258686e-02 -1.15931496e-01  7.94935971e-03 -2.28155423e-02
   -3.21538746e-03  6.25680946e-03  2.35794783e-02  5.75276092e-02
   -1.55696347e-01  4.26145270e-03  1.97074451e-02 -1.73442494e-02
    1.05062492e-01  4.56507877e-02  2.70202875e-01  5.43720201e-02]
  [ 2.20925193e-02  4.72142622e-02  2.88980119e-02  7.62598962e-02
    1.50937259e-01 -1.34362340e-01 -3.81070450e-02  7.07404688e-02
    8.49955752e-02 -1.11373425e-01  7.73486868e-03 -2.31765714e-02
   -5.87033108e-03  3.17306072e-03  2.58065611e-02  5.76197430e-02
   -1.53101742e-01  6.40135631e-03  2.22533830e-02 -1.63127463e-02
    1.05742775e-01  4.59881462e-02  2.66049057e-01  5.24020195e-02]
  [ 2.34547928e-02  4.68440056e-02  2.83318944e-02  7.98197240e-02
    1.51688203e-01 -1.34204179e-01 -3.87502685e-02  7.02475086e-02
    8.44197720e-02 -1.15661144e-01  7.12094828e-03 -2.10390706e-02
   -2.61823647e-03  5.95434289e-03  2.44969502e-02  5.71427941e-02
   -1.55511960e-01  5.24070486e-03  1.89326014e-02 -1.64118465e-02
    1.04824513e-01  4.68217283e-02  2.68508941e-01  5.47876656e-02]
  [ 2.35031489e-02  4.68677580e-02  2.83200145e-02  7.97451437e-02
    1.51711345e-01 -1.34256229e-01 -3.87969166e-02  7.02833682e-02
    8.44551325e-02 -1.15611956e-01  7.25921616e-03 -2.10440811e-02
   -2.60410458e-03  5.93687315e-03  2.45016888e-02  5.70349470e-02
   -1.55402407e-01  5.19045442e-03  1.89729109e-02 -1.64379720e-02
    1.04795069e-01  4.67085689e-02  2.68403292e-01  5.47180623e-02]
  [ 2.36666668e-02  4.56331447e-02  2.93709151e-02  8.05736631e-02
    1.52082860e-01 -1.32452458e-01 -3.76156121e-02  7.00673163e-02
    8.34512413e-02 -1.14647180e-01  6.74233958e-03 -1.90071706e-02
   -2.88706273e-03  4.47905064e-03  2.56108046e-02  5.67482263e-02
   -1.55154824e-01  6.67842850e-03  1.83679126e-02 -1.57558601e-02
    1.05104215e-01  4.80772778e-02  2.66482711e-01  5.53783402e-02]
  [ 2.67137345e-02  4.42694575e-02  2.96287015e-02  7.91661739e-02
    1.39212757e-01 -1.26554966e-01 -3.43116671e-02  6.78251609e-02
    8.09424669e-02 -1.07826591e-01  3.63612175e-03 -2.16909554e-02
    1.20388716e-03  1.08957393e-02  2.13575773e-02  5.82555383e-02
   -1.49498105e-01  4.71137837e-03  1.82388164e-02 -1.93745065e-02
    9.98868942e-02  4.69598845e-02  2.59003878e-01  5.09020314e-02]
  [ 3.84171978e-02  3.98471653e-02  3.91711704e-02  9.33120549e-02
    1.46497175e-01 -1.30936876e-01 -3.60560566e-02  6.88827410e-02
    7.51366839e-02 -1.24362811e-01 -8.55503604e-03 -8.40276293e-03
    1.35236280e-02  1.32140052e-02  1.82588957e-02  6.03778288e-02
   -1.70138463e-01  7.06844032e-03  4.41738032e-03 -2.21369658e-02
    1.03971161e-01  5.76352850e-02  2.68423617e-01  5.88615239e-02]
  [ 5.61331064e-02  3.82201038e-02  5.19167110e-02  1.01225555e-01
    1.38379395e-01 -1.23725899e-01 -3.84288356e-02  6.58076257e-02
    6.39930815e-02 -1.40068665e-01 -2.35748067e-02  2.60252506e-04
    2.87014544e-02  2.40893103e-02  1.30561003e-02  6.69813454e-02
   -1.80763915e-01  5.76185063e-03 -4.35105152e-03 -2.21627560e-02
    9.92049128e-02  6.67248368e-02  2.64741272e-01  5.88590205e-02]
  [ 5.27103394e-02  3.99173945e-02  4.89693955e-02  9.71962363e-02
    1.30851001e-01 -1.21773981e-01 -3.53468657e-02  6.61070645e-02
    6.48198128e-02 -1.33186772e-01 -2.35236436e-02 -4.54846211e-03
    2.82182097e-02  2.92815007e-02  9.00979806e-03  6.85876533e-02
   -1.72937810e-01  2.59935111e-03  8.87550414e-04 -2.30278280e-02
    9.55039114e-02  6.40109554e-02  2.59071320e-01  5.41868284e-02]
  [ 6.22213930e-02  3.31964120e-02  5.80770187e-02  9.84014124e-02
    1.36725307e-01 -1.07688658e-01 -3.71951908e-02  6.02557063e-02
    5.59605882e-02 -1.32689163e-01 -2.13158093e-02  1.49506778e-02
    3.13468799e-02  1.45939924e-02  2.37661526e-02  5.94304726e-02
   -1.69170931e-01  1.55863054e-02 -1.35036055e-02 -1.64588224e-02
    9.86341164e-02  6.96098506e-02  2.41537988e-01  6.00173622e-02]
  [ 3.68133336e-02  3.88823748e-02  3.96067835e-02  8.88490677e-02
    1.52917057e-01 -1.17208950e-01 -3.31437662e-02  6.37837574e-02
    7.27922916e-02 -1.13231242e-01  5.76891005e-04  3.58695723e-03
    1.23852519e-02 -9.47024673e-04  3.16116363e-02  4.86157984e-02
   -1.51182801e-01  1.69846993e-02  4.53005545e-03 -1.22356601e-02
    1.03826143e-01  5.48490323e-02  2.42970675e-01  6.10582530e-02]
  [ 3.17751467e-02  2.94923410e-02  4.16499078e-02  7.79817849e-02
    1.57695770e-01 -9.10228416e-02 -3.57849747e-02  5.60844839e-02
    6.60323128e-02 -9.67342407e-02  1.37733314e-02  3.77393514e-02
    1.09242182e-02 -2.10298374e-02  5.72424680e-02  3.36649865e-02
   -1.20340988e-01  2.65942048e-02  1.29342638e-03  5.91270067e-03
    9.46156904e-02  4.85171117e-02  2.03719378e-01  6.31770045e-02]
  [ 3.35354656e-02  2.17184853e-02  5.59702367e-02  7.66398162e-02
    1.46672219e-01 -6.09111711e-02 -5.50940186e-02  4.78504263e-02
    4.24974188e-02 -9.02897418e-02  2.30983943e-02  5.93957156e-02
    2.39247903e-02 -3.18604819e-02  7.86190629e-02  3.04725040e-02
   -1.02093101e-01  3.18911932e-02 -1.88567620e-02  1.64080225e-02
    8.22752640e-02  4.82490212e-02  1.76609546e-01  7.31343925e-02]
  [ 3.69969122e-02  2.07941923e-02  5.68590276e-02  7.72879571e-02
    1.46934390e-01 -5.98657355e-02 -5.39770052e-02  4.74950895e-02
    4.18228358e-02 -9.47269574e-02  1.97410285e-02  5.87697625e-02
    2.54763011e-02 -2.95263231e-02  7.62108788e-02  3.20993811e-02
   -1.04925498e-01  3.17672715e-02 -2.09321994e-02  1.60406027e-02
    8.32443684e-02  5.01682423e-02  1.78034678e-01  7.20392913e-02]
  [ 2.72087753e-02  1.86109468e-02  7.02236891e-02  7.51795173e-02
    1.40132964e-01 -2.88168993e-02 -7.91545808e-02  3.53822783e-02
    9.37159173e-03 -8.95826817e-02  3.44136544e-02  7.63201714e-02
    3.39035168e-02 -3.94348316e-02  1.05686888e-01  2.60251947e-02
   -9.22854766e-02  3.81164066e-02 -4.47294042e-02  2.59296130e-02
    7.30438158e-02  5.27559370e-02  1.56402051e-01  8.33916813e-02]
  [ 4.31133509e-02  1.12998141e-02  7.63793215e-02  7.88858235e-02
    1.26575455e-01 -1.60676111e-02 -7.22217187e-02  3.81282121e-02
    1.17193684e-02 -1.03967562e-01  2.44916845e-02  7.25572854e-02
    3.78749445e-02 -2.10960619e-02  9.35725346e-02  3.29660475e-02
   -9.19218883e-02  3.47878411e-02 -5.40056750e-02  2.38499064e-02
    7.36941248e-02  5.50975651e-02  1.47897348e-01  7.73856044e-02]
  [ 7.20750839e-02  6.14173058e-03  1.07243963e-01  8.64735991e-02
    1.28958970e-01  5.20410761e-03 -6.45541176e-02  3.75609584e-02
    2.03790143e-02 -1.47659212e-01 -1.36644617e-02  7.40827993e-02
    4.95498627e-02  1.85030513e-02  6.77390844e-02  5.19692302e-02
   -1.12274781e-01  2.98292525e-02 -7.26733804e-02  1.24940313e-02
    7.34940320e-02  6.95941895e-02  1.42840385e-01  5.66570163e-02]
  [ 8.40015411e-02  1.89453829e-02  1.37972310e-01  9.42625999e-02
    1.46798119e-01  9.37157683e-03 -8.40030462e-02  4.57436629e-02
    2.53726710e-02 -1.77122712e-01 -3.61008570e-02  7.93002248e-02
    5.70945889e-02  4.22192141e-02  6.64131492e-02  6.76973984e-02
   -1.37393057e-01  2.63214521e-02 -9.06440094e-02  6.27613440e-03
    7.46930465e-02  7.15049058e-02  1.55868933e-01  4.39767241e-02]
  [ 8.00848752e-02  1.57254841e-02  1.28633112e-01  8.92139226e-02
    1.37244746e-01  9.99965519e-03 -7.54160360e-02  4.39710505e-02
    2.47778092e-02 -1.62274137e-01 -2.88374759e-02  7.61943683e-02
    5.33656925e-02  3.79476175e-02  6.51698261e-02  6.27752244e-02
   -1.23924673e-01  2.62701083e-02 -8.20891485e-02  7.56944623e-03
    7.21556395e-02  6.77928627e-02  1.46695837e-01  4.46162522e-02]
  [ 6.56094849e-02  4.20163106e-03  9.28006247e-02  8.77716541e-02
    1.25814095e-01 -3.52314673e-03 -7.32601285e-02  3.67550477e-02
    1.54240765e-02 -1.38084620e-01  3.65871191e-03  7.52311200e-02
    5.13576865e-02 -2.69822776e-04  8.11154693e-02  4.43888195e-02
   -1.06638730e-01  3.16682085e-02 -7.02336654e-02  1.84456967e-02
    7.74954632e-02  6.49457425e-02  1.48135498e-01  6.87608644e-02]]]

In [ ]:
predictions.shape

(1, 24, 24)

: